### ISSUE TITLE
Broadening search of the book field in transaction and inventory entries.

### ISSUE THREAD

**Issue by chelseakaylamarie** [sfu-dhil/bep#89] opened 2021-07-16 19:29 UTC
**Is your feature request related to a problem? Please describe.**
Right now, when searching in the book field, we can only retrieve and link a book to a transaction or inventory entry if we enter the title as it is in the "Title field." No results are found if we enter a variant or uniform title.

**Describe the solution you'd like**
Ideally we would like it if we could enter keywords or phrases from any of the following fields: Title, Uniform Title, Variant title. 

**Describe alternatives you've considered**
If it isn't possible to do a keyword or phrase search, we should enter a description under the "Books" field such as "enter title as it appears on the ESTC or the 'Title' field of the book entry."

**User Information**
This is mainly for those entering data at this point, it can be difficult to find the correct book.

**Additional context**
<img width="797" alt="Screenshot 2021-07-16 120719" src="https://user-images.githubusercontent.com/79331176/125998938-57f03e9e-97ff-4105-8f21-948ad7204760.png">
(Results are only yielded when entering the title as it appears in the "Title" field of the book entry)
<img width="794" alt="Screenshot 2021-07-16 120744" src="https://user-images.githubusercontent.com/79331176/125998952-f4b72030-c3c3-42b9-8b4f-47224231c8f9.png">
(Entering the uniform title yields no results)

**Comment by ubermichael** [comment] 2021-07-22 17:29
Duplicate of #90

**Closed as completed by ubermichael** 2021-07-22 17:29 UTC
Labels: feature
